/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppAchievementsRouteImport } from './routes/app.achievements'
import { Route as AppSightingIdRouteImport } from './routes/app.sighting.$id'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/app/new',
  path: '/app/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAchievementsRoute = AppAchievementsRouteImport.update({
  id: '/app/achievements',
  path: '/app/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSightingIdRoute = AppSightingIdRouteImport.update({
  id: '/app/sighting/$id',
  path: '/app/sighting/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/app/achievements': typeof AppAchievementsRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/app/sighting/$id': typeof AppSightingIdRoute
}
export interface FileRoutesByTo {
  '/app/achievements': typeof AppAchievementsRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app': typeof AppIndexRoute
  '/app/sighting/$id': typeof AppSightingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app/achievements': typeof AppAchievementsRoute
  '/app/new': typeof AppNewRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/': typeof AppIndexRoute
  '/app/sighting/$id': typeof AppSightingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app/achievements'
    | '/app/new'
    | '/app/profile'
    | '/app/search'
    | '/app/'
    | '/app/sighting/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app/achievements'
    | '/app/new'
    | '/app/profile'
    | '/app/search'
    | '/app'
    | '/app/sighting/$id'
  id:
    | '__root__'
    | '/app/achievements'
    | '/app/new'
    | '/app/profile'
    | '/app/search'
    | '/app/'
    | '/app/sighting/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppAchievementsRoute: typeof AppAchievementsRoute
  AppNewRoute: typeof AppNewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSightingIdRoute: typeof AppSightingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/new': {
      id: '/app/new'
      path: '/app/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/achievements': {
      id: '/app/achievements'
      path: '/app/achievements'
      fullPath: '/app/achievements'
      preLoaderRoute: typeof AppAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sighting/$id': {
      id: '/app/sighting/$id'
      path: '/app/sighting/$id'
      fullPath: '/app/sighting/$id'
      preLoaderRoute: typeof AppSightingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppAchievementsRoute: AppAchievementsRoute,
  AppNewRoute: AppNewRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppSightingIdRoute: AppSightingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
